# Generated by Django 4.2.3 on 2023-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('inprogress', 'In Progress'), ('done', 'Done')], max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=230)),
            ],
        ),
    ]
